/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as SidebarIndexRouteImport } from './../routes/_sidebar/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarExploreRouteImport } from './../routes/_sidebar/explore'
import { Route as SidebarConfigRouteImport } from './../routes/_sidebar/config'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarExploreRoute = SidebarExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigRoute = SidebarConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/config': typeof SidebarConfigRoute
  '/explore': typeof SidebarExploreRoute
  '/profile': typeof SidebarProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarIndexRoute
  '/config': typeof SidebarConfigRoute
  '/explore': typeof SidebarExploreRoute
  '/profile': typeof SidebarProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/': typeof SidebarIndexRoute
  '/_sidebar/config': typeof SidebarConfigRoute
  '/_sidebar/explore': typeof SidebarExploreRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/explore'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/explore' | '/profile'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/'
    | '/_sidebar/config'
    | '/_sidebar/explore'
    | '/_sidebar/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/explore': {
      id: '/_sidebar/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof SidebarExploreRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/config': {
      id: '/_sidebar/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof SidebarConfigRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarIndexRoute: typeof SidebarIndexRoute
  SidebarConfigRoute: typeof SidebarConfigRoute
  SidebarExploreRoute: typeof SidebarExploreRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarIndexRoute: SidebarIndexRoute,
  SidebarConfigRoute: SidebarConfigRoute,
  SidebarExploreRoute: SidebarExploreRoute,
  SidebarProfileRoute: SidebarProfileRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
