import json
import logging
import warnings
import os
import re
import urllib
import uuid
from datetime import datetime, timezone
from io import StringIO, BytesIO
from pathlib import Path
from abc import ABC, abstractmethod
from typing import Generic, TypeVar, NoReturn
from sqlalchemy import (
    DateTime,
    Engine,
    create_engine,
    MetaData,
    Table,
    Column,
    String,
    Text,
    insert,
    inspect,
    select,
    delete,
    null,
    event,
    text,
)
from sqlalchemy.schema import CreateSchema
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.exc import DatabaseError, ProgrammingError, OperationalError, IntegrityError

import yaml
from pyspark.sql import DataFrame, SparkSession, functions as F
from databricks.sdk.errors import NotFound
from databricks.sdk.service.workspace import ImportFormat

from databricks.labs.dqx.config import (
    TableChecksStorageConfig,
    LakebaseChecksStorageConfig,
    FileChecksStorageConfig,
    WorkspaceFileChecksStorageConfig,
    InstallationChecksStorageConfig,
    BaseChecksStorageConfig,
    VolumeFileChecksStorageConfig,
    RunConfig,
)
from databricks.labs.dqx.errors import (
    CheckDownloadError,
    InvalidCheckError,
    InvalidConfigError,
    UnsafeSqlQueryError,
)
from databricks.sdk import WorkspaceClient

from databricks.labs.dqx.checks_serializer import (
    ChecksSerializer,
    ChecksDeserializer,
    SerializerFactory,
    ChecksNormalizer,
)
from databricks.labs.dqx.checks_validator import ChecksValidator
from databricks.labs.dqx.rule_fingerprint import compute_rule_set_fingerprint_by_metadata
from databricks.labs.dqx.rule import compute_rule_fingerprint
from databricks.labs.dqx.utils import get_file_extension, safe_json_load
from databricks.labs.dqx.config_serializer import ConfigSerializer
from databricks.labs.dqx.installer.mixins import InstallationMixin
from databricks.labs.dqx.io import TABLE_PATTERN
from databricks.labs.dqx.telemetry import telemetry_logger

logger = logging.getLogger(__name__)
T = TypeVar("T", bound=BaseChecksStorageConfig)

# Maps each versioning column to its SQL type for Delta (Spark SQL) and Lakebase (PostgreSQL).
# The iteration order is preserved; add new columns here only — _ensure_versioning_columns
# in both storage handlers derive everything from this mapping.
_VERSIONING_COLUMN_TYPES_DELTA = {
    "created_at": "TIMESTAMP",
    "rule_fingerprint": "STRING",
    "rule_set_fingerprint": "STRING",
}
_VERSIONING_COLUMN_TYPES_LAKEBASE = {
    "created_at": "TIMESTAMP",
    "rule_fingerprint": "VARCHAR(255)",
    "rule_set_fingerprint": "VARCHAR(255)",
}
_VERSIONING_COLUMNS = tuple(_VERSIONING_COLUMN_TYPES_DELTA)

CHECKS_TABLE_SCHEMA = (
    "name STRING, criticality STRING, check STRUCT<function STRING, for_each_column ARRAY<STRING>,"
    " arguments MAP<STRING, STRING>>, filter STRING, run_config_name STRING, user_metadata MAP<STRING, STRING>,"
    " created_at TIMESTAMP, rule_fingerprint STRING, rule_set_fingerprint STRING"
)


class DataFrameConverter:
    """
    Handles conversion between DataFrames and check dictionaries.
    """

    @staticmethod
    def from_dataframe(
        df: DataFrame, run_config_name: str = "default", rule_set_fingerprint: str | None = None
    ) -> list[dict]:
        """
        Converts a list of quality checks defined in a DataFrame to a list of quality checks
        defined as Python dictionaries.

        Args:
            df: DataFrame with data quality check rules. Each row should define a check. Rows should
            have the following columns:
                - *name* - Name that will be given to a resulting column. Autogenerated if not provided.
                - *criticality* (optional) - Possible values are *error* (data going only into "bad" dataframe) and *warn* (data is going into both dataframes).
                - *check* - DQX check function used in the check; A *StructType* column defining the data quality check.
                - *filter* - Expression for filtering data quality checks.
                - *run_config_name* (optional) - Run configuration name for storing checks across runs.
                - *user_metadata* (optional) - User-defined key-value pairs added to metadata generated by the check.
            run_config_name: Run configuration name for filtering quality rules, e.g. input table or job name (use "default" if not provided).
            rule_set_fingerprint: Optional SHA-256 fingerprint of the rule set to load. When provided, filters to rules
                with this specific fingerprint, in addition to the run_config_name filter, instead of loading the latest batch.

        Returns:
                List of data quality check specifications as a Python dictionary
        """
        filtered_df = df.where(F.col("run_config_name") == run_config_name)

        has_versioning = "rule_set_fingerprint" in df.columns
        if has_versioning:
            # Filter by fingerprint or to the latest batch by created_at.
            # Use desc_nulls_last() so legacy rows with NULL created_at/rule_set_fingerprint
            # do not sort ahead of versioned rows in descending order.
            if not rule_set_fingerprint:
                result = (
                    filtered_df.select(F.col("rule_set_fingerprint"))
                    .orderBy(
                        F.col("created_at").desc_nulls_last(),
                        F.col("rule_set_fingerprint").desc_nulls_last(),
                    )
                    .limit(1)
                    .collect()
                )
                if not result:
                    return []
                rule_set_fingerprint = result[0][0]

            # May be None for legacy rows with NULL rule_set_fingerprint; load all rows for run_config_name
            if rule_set_fingerprint is not None:
                filtered_df = filtered_df.where(F.col("rule_set_fingerprint") == rule_set_fingerprint)

        check_rows = filtered_df.collect()
        collect_limit = 500
        if len(check_rows) > collect_limit:
            warnings.warn(
                f"Collecting large number of rows from DataFrame: {len(check_rows)}",
                category=UserWarning,
                stacklevel=2,
            )

        checks = []
        for row in check_rows:
            check_dict = {
                "name": row.name,
                "criticality": row.criticality,
                "check": {
                    "function": row.check["function"],
                    "arguments": (
                        {k: safe_json_load(v) for k, v in row.check["arguments"].items()}
                        if row.check["arguments"] is not None
                        else {}
                    ),
                },
            }
            if "for_each_column" in row.check and row.check["for_each_column"]:
                check_dict["check"]["for_each_column"] = row.check["for_each_column"]
            if row.filter is not None:
                check_dict["filter"] = row.filter
            if row.user_metadata is not None:
                check_dict["user_metadata"] = row.user_metadata
            # Denormalize special markers back to objects
            checks.append(ChecksNormalizer.denormalize_value(check_dict))
        return checks

    @staticmethod
    def to_dataframe(
        spark: SparkSession,
        checks: list[dict],
        run_config_name: str = "default",
        rule_set_fingerprint: str | None = None,
        created_at: datetime | None = None,
    ) -> DataFrame:
        """
        Converts a list of quality checks defined as Python dictionaries to a DataFrame.

        Args:
            spark: Spark session.
            checks: list of check specifications as Python dictionaries. Each check consists of the following fields:
                - *check* - Column expression to evaluate. This expression should return string value if it's evaluated to
                   true (it will be used as an error/warning message) or *null* if it's evaluated to *false*
                - *name* - Name that will be given to a resulting column. Autogenerated if not provided
                - *criticality* (optional) - Possible values are *error* (data going only into "bad" dataframe) and *warn*
                   (data is going into both dataframes)
                - *filter* (optional) - Expression for filtering data quality checks
                - *user_metadata* (optional) - User-defined key-value pairs added to metadata generated by the check.
            run_config_name: Run configuration name for storing quality checks across runs, e.g. input table or job name (use "default" if not provided).
            rule_set_fingerprint: Optional precomputed SHA-256 fingerprint of the rule set. When provided, avoids recomputing it.
            created_at: Timestamp to stamp each row with. Defaults to the current UTC time when not provided.
                Pass an explicit value in tests or whenever a deterministic timestamp is required.

        Returns:
            DataFrame with data quality check rules

        Raises:
            InvalidCheckError: If any check is invalid or unsupported.
        """
        status = ChecksValidator.validate_checks(checks, None)
        if status.has_errors:
            raise InvalidCheckError(str(status))

        normalized_for_serialization = ChecksNormalizer.normalize(checks)

        rule_set_fingerprint = (
            rule_set_fingerprint
            if rule_set_fingerprint is not None
            else compute_rule_set_fingerprint_by_metadata(checks)
        )

        effective_created_at = created_at if created_at is not None else datetime.now(timezone.utc)
        dq_rule_rows = []
        for check in normalized_for_serialization:
            check_inner = check.get("check") or {}
            func_args = check_inner.get("arguments") or {}
            # Values are already normalized by ChecksNormalizer.normalize; json.dumps for MAP<STRING, STRING>
            json_arguments = {k: json.dumps(v) for k, v in func_args.items()}

            check_struct = {
                "function": check_inner.get("function"),
                "for_each_column": check_inner.get("for_each_column") or [],
                "arguments": json_arguments,
            }

            dq_rule_rows.append(
                [
                    check.get("name"),
                    check.get("criticality", "error"),
                    check_struct,
                    check.get("filter"),
                    run_config_name,
                    check.get("user_metadata"),
                    effective_created_at,
                    compute_rule_fingerprint(check),
                    rule_set_fingerprint,
                ]
            )
        return spark.createDataFrame(dq_rule_rows, CHECKS_TABLE_SCHEMA)


class ChecksStorageHandler(ABC, Generic[T]):
    """
    Abstract base class for handling storage of quality rules (checks).
    """

    @abstractmethod
    def load(self, config: T) -> list[dict]:
        """
        Load quality rules from the source.
        The returned checks can be used as input for *apply_checks_by_metadata* or
        *apply_checks_by_metadata_and_split* functions.

        Args:
            config: configuration for loading checks, including the table location and run configuration name.

        Returns:
            list of dq rules or raise an error if checks file is missing or is invalid.
        """

    @abstractmethod
    def save(self, checks: list[dict], config: T) -> None:
        """Save quality rules to the target."""


class TableChecksStorageHandler(ChecksStorageHandler[TableChecksStorageConfig]):
    """
    Handler for storing quality rules (checks) in a Delta table in the workspace.
    """

    def __init__(self, ws: WorkspaceClient, spark: SparkSession):
        self.ws = ws
        self.spark = spark

    @telemetry_logger("load_checks", "table")
    def load(self, config: TableChecksStorageConfig) -> list[dict]:
        """
        Load checks (dq rules) from a Delta table in the workspace.

        Args:
            config: configuration for loading checks, including the table location and run configuration name.

        Returns:
            list of dq rules or raise an error if checks table is missing or is invalid.

        Raises:
            NotFound: if the table does not exist in the workspace
        """
        logger.info(f"Loading quality rules (checks) from table '{config.location}'")
        if not self._table_exists(config.location):
            raise NotFound(f"Checks table '{config.location}' does not exist in the workspace")

        rules_df = self.spark.read.table(config.location)
        return (
            DataFrameConverter.from_dataframe(
                rules_df, run_config_name=config.run_config_name, rule_set_fingerprint=config.rule_set_fingerprint
            )
            or []
        )

    @telemetry_logger("save_checks", "table")
    def save(self, checks: list[dict], config: TableChecksStorageConfig) -> None:
        """
        Save checks to a Delta table in the workspace.

        Args:
            checks: list of dq rules to save
            config: configuration for saving checks, including the table location and run configuration name.

        Raises:
            InvalidCheckError: If any check is invalid or unsupported.
            UnsafeSqlQueryError: If run_config_name contains unsafe SQL (e.g. DML/DDL keywords) when mode is overwrite.

        Notes:
            Idempotency: If the table already contains a rule set with the same rule_set_fingerprint for this
            run_config_name, the save is skipped and the method returns without writing. This applies regardless
            of config.mode (including "overwrite"). So a call with mode="overwrite" and a checks payload
            that hashes to an existing fingerprint will not overwrite (e.g. if only non-fingerprinted metadata changed).

            Mode behavior:
            - **overwrite**: If the fingerprint differs, replaces all rows for this run_config_name with the new
              checks (via Delta replaceWhere). If the fingerprint matches, no write is performed.
            - **append**: If the fingerprint differs, appends the new checks as additional rows for this
              run_config_name (multiple versions accumulate). If the fingerprint matches, no write is performed.

            Concurrency: The idempotency check is not atomic for Delta tables. The check-then-write sequence
            (read fingerprint → skip if found → write) is not wrapped in a transaction, so two concurrent
            callers saving the same rule set may both pass the check and both write, producing duplicate rows
            in append mode or redundant overwrites in overwrite mode. This is benign in practice because
            duplicate rows with the same fingerprint are functionally equivalent and the load path always
            returns the latest version. For strict once-only guarantees use a single writer or apply
            external coordination (e.g. a Databricks job with a single task).
        """

        if not checks:
            logger.info("No checks available. Skipping saving to a delta table.")
            return

        if config.mode == "overwrite" and not re.fullmatch(r"[\w.\-]+", config.run_config_name):
            raise UnsafeSqlQueryError(
                f"run_config_name must not contain unsafe SQL characters. "
                f"Only word characters (a-z, A-Z, 0-9, _), '.', and '-' are allowed; got '{config.run_config_name}'."
            )

        logger.info(f"Saving quality rules (checks) to table '{config.location}'")
        rule_set_fingerprint = compute_rule_set_fingerprint_by_metadata(checks)
        rules_df = DataFrameConverter.to_dataframe(
            self.spark, checks, run_config_name=config.run_config_name, rule_set_fingerprint=rule_set_fingerprint
        )

        # Skip save if rule_set_fingerprint already exists in existing table
        if self._table_exists(config.location):
            existing_df = self.spark.read.table(config.location)
            columns_added = self._ensure_versioning_columns(config.location, existing_df)
            if columns_added:
                # Schema changed — re-read so the DataFrame includes the new columns.
                existing_df = self.spark.read.table(config.location)
            exists = not existing_df.filter(
                (F.col("run_config_name") == config.run_config_name)
                & (F.col("rule_set_fingerprint") == rule_set_fingerprint)
            ).isEmpty()
            if exists:
                logger.info(
                    f"Checks with rule_set_fingerprint '{rule_set_fingerprint}' already exist in table '{config.location}'"
                )
                return

        writer = rules_df.write
        if config.mode == "overwrite":
            predicate = f"run_config_name = '{config.run_config_name}'"
            writer = writer.option("replaceWhere", predicate)
        writer.saveAsTable(config.location, mode=config.mode)

    def _table_exists(self, location: str) -> bool:
        """Check if a Delta table exists in the workspace.

        Args:
            location: Full table name (e.g., "schema.table" or "`schema`.`table`")

        Returns:
            True if the table exists, False otherwise.
        """
        try:
            # to be handled by the sdk: https://github.com/databricks/databricks-sdk-py/issues/1266
            url_safe_table_name = urllib.parse.quote(location.replace("`", ""))
            self.ws.tables.get(full_name=url_safe_table_name)
            return True
        except NotFound:
            return False

    def _ensure_versioning_columns(self, location: str, existing_df: DataFrame | None = None) -> bool:
        """Add missing versioning columns to an existing Delta table.

        Args:
            location: Full table name (e.g., "catalog.schema.table").
            existing_df: Optional pre-read DataFrame for the table. When provided, its schema is
                used instead of re-reading the table, avoiding a redundant read.

        Returns:
            True if columns were added, False if all versioning columns already existed.
        """
        df = existing_df if existing_df is not None else self.spark.read.table(location)
        existing_columns = {f.name for f in df.schema.fields}
        missing = [col for col in _VERSIONING_COLUMNS if col not in existing_columns]
        if not missing:
            return False

        quoted = ".".join(f"`{part}`" for part in location.replace("`", "").split("."))
        for col in missing:
            col_type = _VERSIONING_COLUMN_TYPES_DELTA[col]
            self.spark.sql(f"ALTER TABLE {quoted} ADD COLUMN {col} {col_type}")
        logger.info(f"Added versioning columns {missing} to table '{location}'.")
        return True


class LakebaseChecksStorageHandler(ChecksStorageHandler[LakebaseChecksStorageConfig]):
    """
    Handler for storing dq rules (checks) in a Lakebase table.
    """

    def __init__(
        self,
        ws: WorkspaceClient,
        spark: SparkSession,
        engine: Engine | None = None,
    ):
        self.ws = ws
        self.spark = spark
        self.engine = engine

    def _get_connection_url(self, config: LakebaseChecksStorageConfig) -> str:
        """
        Generate a Lakebase connection URL.

        Args:
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            Lakebase connection URL.
        """
        if not config.instance_name:
            raise InvalidConfigError("instance_name must be provided for Lakebase storage")
        if not config.location:
            raise InvalidConfigError("location must be provided for Lakebase storage")

        instance = self.ws.database.get_database_instance(config.instance_name)
        host = instance.read_write_dns
        prefix = "postgresql+psycopg2"
        port = config.port
        database = config.database_name
        user = config.client_id if config.client_id else self.ws.current_user.me().user_name

        return f"{prefix}://{user}@{host}:{port}/{database}?sslmode=require"

    def _prepare_before_connect(self, config: LakebaseChecksStorageConfig):
        """
        Prepare the before_connect event listener with the instance_name captured in closure.

        Args:
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            The _before_connect event listener function.

        Raises:
            InvalidConfigError: If instance_name is not provided.
        """
        if not config.instance_name:
            raise InvalidConfigError("instance_name must be provided for Lakebase storage")

        instance_name = config.instance_name

        def _before_connect(_dialect, _conn_rec, _cargs, cparams) -> None:
            cred = self.ws.database.generate_database_credential(
                request_id=str(uuid.uuid4()), instance_names=[instance_name]
            )
            cparams["password"] = cred.token

        return _before_connect

    def get_engine(self, config: LakebaseChecksStorageConfig) -> Engine:
        """
        Create a SQLAlchemy engine for the Lakebase instance.

        Args:
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            SQLAlchemy engine for the Lakebase instance.
        """
        engine_url = self._get_connection_url(config)
        engine = create_engine(
            engine_url,
            pool_recycle=45 * 60,  # recycle connections every 45 minutes
            connect_args={'sslmode': 'require'},
            pool_size=4,
        )
        event.listen(engine, "do_connect", self._prepare_before_connect(config))
        return engine

    @staticmethod
    def get_table_definition(schema_name: str, table_name: str, versioning: bool = True) -> Table:
        """
        Create a SQLAlchemy table definition for storing DQ rules (checks) in Lakebase.

        Args:
            schema_name: The schema where the checks table is located.
            table_name: The table where the checks are stored.
            versioning: If True (default), include versioning columns (created_at, rule_fingerprint,
                rule_set_fingerprint). Pass False for legacy tables that predate versioning support.

        Returns:
            SQLAlchemy table definition for the Lakebase instance.
        """
        columns = [
            Column("name", String(255)),
            Column("criticality", String(50), server_default="error"),
            Column("check", JSONB),
            Column("filter", Text),
            Column("run_config_name", String(255), server_default="default"),
            Column("user_metadata", JSONB),
        ]
        if versioning:
            columns += [
                Column("created_at", DateTime),
                Column("rule_fingerprint", String(64)),
                Column("rule_set_fingerprint", String(64)),
            ]
        return Table(table_name, MetaData(schema=schema_name), *columns)

    @staticmethod
    def _normalize_checks(checks: list[dict], config: LakebaseChecksStorageConfig) -> list[dict]:
        """
        Normalize the checks to be compatible with the Lakebase table.
        This includes normalizing special values for JSON serialization and structuring
        the checks for the Lakebase table schema.

        Args:
            checks: List of dq rules (checks) to normalize.
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            List of normalized dq rules (checks).
        """
        # First normalize special values for JSON serialization
        normalized_for_serialization = ChecksNormalizer.normalize(checks)

        created_at = datetime.now(timezone.utc)
        run_config_name = config.run_config_name
        rule_set_fingerprint = compute_rule_set_fingerprint_by_metadata(checks)

        normalized_checks = []
        for check in normalized_for_serialization:
            user_metadata = check.get("user_metadata")
            normalized_check = {
                "name": check.get("name"),
                "criticality": check.get("criticality", "error"),
                "check": check.get("check"),
                "filter": check.get("filter"),
                "run_config_name": run_config_name,
                "user_metadata": null() if user_metadata is None else user_metadata,
                "created_at": created_at,
                "rule_fingerprint": compute_rule_fingerprint(check),
                "rule_set_fingerprint": rule_set_fingerprint,
            }
            normalized_checks.append(normalized_check)
        return normalized_checks

    def _save_checks_to_lakebase(self, checks: list[dict], config: LakebaseChecksStorageConfig, engine: Engine) -> None:
        """
        Save dq rules (checks) to a Lakebase table.

        Args:
            checks: List of dq rules (checks) to save.
            config: Configuration for saving and loading checks to Lakebase.
            engine: SQLAlchemy engine for the Lakebase instance.

        Returns:
            None

        Raises:
            OperationalError: If connecting to the database fails.

        Notes:
            Idempotency: If the table already contains a rule set with the same rule_set_fingerprint for this
            run_config_name, the save is skipped and the method returns without writing or deleting. This applies
            regardless of config.mode (including "overwrite"). The fingerprint check is performed before any
            overwrite delete, so an existing matching fingerprint always results in a no-op.

            Mode behavior:
            - **overwrite**: If the fingerprint differs, deletes all rows for this run_config_name and inserts
              the new checks. If the fingerprint matches, no write is performed.
            - **append**: If the fingerprint differs, inserts the new checks (existing rows remain; multiple
              versions accumulate). If the fingerprint matches, no write is performed.
        """
        if not checks:
            logger.info("No checks available. Skipping saving to a lakebase instance.")
            return

        try:
            with engine.connect() as conn:
                pass
        except OperationalError as e:
            logger.error(
                f"Failed to connect to database '{config.database_name}'. "
                f"Please verify the database exists and the user has access: {e}"
            )
            raise

        with engine.begin() as conn:
            if not conn.dialect.has_schema(conn, config.schema_name):
                conn.execute(CreateSchema(config.schema_name))
                logger.info(f"Successfully created schema '{config.schema_name}'.")

        with engine.begin() as conn:
            table = self.get_table_definition(config.schema_name, config.table_name)
            table.metadata.create_all(engine, checkfirst=True)
            logger.info(
                f"Successfully created or verified table '{config.database_name}.{config.schema_name}.{config.table_name}'."
            )
            LakebaseChecksStorageHandler._ensure_versioning_columns(engine, config)

            normalized_checks = self._normalize_checks(checks, config)

            rule_set_fingerprint = normalized_checks[0].get("rule_set_fingerprint")
            exists_rule_set = (
                select(table.c.rule_set_fingerprint)
                .where(
                    table.c.run_config_name == config.run_config_name,
                    table.c.rule_set_fingerprint == rule_set_fingerprint,
                )
                .limit(1)
            )
            if conn.execute(exists_rule_set).first():
                logger.info(f"Checks with rule_set_fingerprint {rule_set_fingerprint} already exist — skipping")
                return

            if config.mode == "overwrite":
                delete_stmt = delete(table).where(table.c.run_config_name == config.run_config_name)
                result = conn.execute(delete_stmt)
                logger.info(f"Deleted {result.rowcount} existing checks for run_config_name '{config.run_config_name}'")

            insert_stmt = insert(table)
            conn.execute(insert_stmt, normalized_checks)
            logger.info(
                f"Inserted {len(normalized_checks)} checks to {config.database_name}.{config.schema_name}.{config.table_name} "
                f"with run_config_name='{config.run_config_name}'"
            )

    @staticmethod
    def _ensure_versioning_columns(engine: Engine, config: LakebaseChecksStorageConfig) -> None:
        """Add missing versioning columns to an existing Lakebase table.

        Skips DDL if all columns already exist.

        Args:
            engine: SQLAlchemy engine for the Lakebase instance.
            config: Configuration for saving and loading checks to Lakebase.
        """
        if LakebaseChecksStorageHandler._rule_set_columns_exists(engine, config.schema_name, config.table_name):
            return

        tbl = f'"{config.schema_name}"."{config.table_name}"'
        with engine.begin() as conn:
            for col, col_type in _VERSIONING_COLUMN_TYPES_LAKEBASE.items():
                conn.execute(text(f"ALTER TABLE {tbl} ADD COLUMN IF NOT EXISTS {col} {col_type}"))
        logger.info(f"Added versioning columns {list(_VERSIONING_COLUMNS)} to table '{config.location}'.")

    def _load_checks_from_lakebase(self, config: LakebaseChecksStorageConfig, engine: Engine) -> list[dict]:
        """
        Load dq rules (checks) from a Lakebase table.

        Args:
            config: Configuration for saving and loading checks to Lakebase.
            engine: SQLAlchemy engine for the Lakebase instance.

        Returns:
            List of dq rules.
        """
        inspector = inspect(engine)
        if not inspector.has_table(config.table_name, schema=config.schema_name):
            raise NotFound(f"Table '{config.location}' does not exist in the Lakebase instance")

        has_versioning = LakebaseChecksStorageHandler._rule_set_columns_exists(
            engine, config.schema_name, config.table_name
        )
        table = self.get_table_definition(config.schema_name, config.table_name, versioning=has_versioning)

        if not has_versioning:
            # Legacy table without versioning columns; load all rows for run_config_name.
            stmt = select(table).where(table.c.run_config_name == config.run_config_name)
        elif config.rule_set_fingerprint:
            logger.info(f"Filtering checks by rule_set_fingerprint='{config.rule_set_fingerprint}'")
            stmt = select(table).where(
                table.c.rule_set_fingerprint == config.rule_set_fingerprint,
                table.c.run_config_name == config.run_config_name,
            )
        else:
            logger.info("No rule_set_fingerprint provided, loading the most recent version.")
            # Exclude legacy rows (NULL versioning cols) when picking latest; use NULLS LAST so
            # legacy rows don't sort first (PostgreSQL sorts NULL first in DESC by default).
            latest_subq = (
                select(table.c.rule_set_fingerprint)
                .where(
                    table.c.run_config_name == config.run_config_name,
                    table.c.rule_set_fingerprint.isnot(None),
                )
                .order_by(
                    table.c.created_at.desc().nulls_last(),
                    table.c.rule_set_fingerprint.desc().nulls_last(),
                )
                .limit(1)
            )
            with engine.connect() as conn:
                latest_rule_set_fingerprint = conn.execute(latest_subq).scalar_one_or_none()
            if latest_rule_set_fingerprint is not None:
                stmt = select(table).where(
                    table.c.rule_set_fingerprint == latest_rule_set_fingerprint,
                    table.c.run_config_name == config.run_config_name,
                )
            else:
                # All rows have NULL fingerprint; load all rows for run_config.
                stmt = select(table).where(table.c.run_config_name == config.run_config_name)

        with engine.connect() as conn:
            result = conn.execute(stmt)
            checks = result.mappings().all()

            logger.info(
                f"Successfully loaded {len(checks)} checks from {config.database_name}.{config.schema_name}.{config.table_name} "
                f"for run_config_name='{config.run_config_name}'"
            )
            if len(checks) == 0:
                logger.warning(
                    f"No checks found in {config.database_name}.{config.schema_name}.{config.table_name} "
                    f"for run_config_name='{config.run_config_name}'. "
                    f"Make sure the profiler has run successfully and saved checks to this location."
                )
            checks_dict = [dict(check) for check in checks]

            # Denormalize special markers back to objects
            return ChecksNormalizer.denormalize(checks_dict)

    @staticmethod
    def _rule_set_columns_exists(engine: Engine, schema: str, table: str) -> bool:
        """
        Check if the rule_fingerprint, rule_set_fingerprint, and created_at columns exist in the Lakebase table.

        Args:
            engine: SQLAlchemy engine for the Lakebase instance.
            schema: Schema name of the Lakebase table.
            table: Table name of the Lakebase table.

        Returns:
            True if the columns exist, False otherwise.
        """

        inspector = inspect(engine)
        if not inspector.has_table(table, schema=schema):
            return False
        cols = inspector.get_columns(table, schema=schema)
        existing_column_names = {col['name'] for col in cols}
        return all(x in existing_column_names for x in _VERSIONING_COLUMNS)

    def _check_for_undefined_table_error(self, e: ProgrammingError, config: LakebaseChecksStorageConfig) -> NoReturn:
        """
        Check if the error is an undefined table error and raise an appropriate exception.

        This method always raises an exception and never returns normally.

        Args:
            e: Programming error to check.
            config: Configuration for saving and loading checks to Lakebase.

        Raises:
            NotFound: If the table does not exist in the Lakebase instance (pgcode 42P01).
            ProgrammingError: Re-raises the original error if it's not an undefined table error.
        """
        pgcode = getattr(getattr(e, 'orig', None), 'pgcode', None)
        postgres_undefined_table_error = '42P01'
        if pgcode == postgres_undefined_table_error:
            raise NotFound(f"Table '{config.location}' does not exist in the Lakebase instance") from e
        raise e

    @telemetry_logger("load_checks", "lakebase")
    def load(self, config: LakebaseChecksStorageConfig) -> list[dict]:
        """
        Load dq rules (checks) from a Lakebase table.

        Args:
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            List of dq rules or error if loading checks fails.

        Raises:
            NotFound: If the table does not exist in the Lakebase instance.
            ProgrammingError: If SQL syntax errors or missing objects (converted to NotFound for missing tables).
            DatabaseError: If other database operations fail (includes OperationalError, IntegrityError, etc.).
        """
        engine = self.engine
        engine_created_internally = False
        if not engine:
            engine = self.get_engine(config)
            engine_created_internally = True

        try:
            return self._load_checks_from_lakebase(config, engine)

        except ProgrammingError as e:
            logger.error(f"Programming error while loading checks from Lakebase: {e}")
            self._check_for_undefined_table_error(e, config)

        except DatabaseError as e:
            logger.error(f"Database error while loading checks from Lakebase: {e}")
            raise

        finally:
            if engine_created_internally:
                engine.dispose()

    @telemetry_logger("save_checks", "lakebase")
    def save(self, checks: list[dict], config: LakebaseChecksStorageConfig) -> None:
        """
        Save dq rules (checks) to a Lakebase table.

        Args:
            checks: List of dq rules (checks) to save.
            config: Configuration for saving and loading checks to Lakebase.

        Returns:
            None

        Raises:
            InvalidCheckError: If any check is invalid or unsupported.
            IntegrityError: If constraint violations occur (e.g., duplicate keys).
            ProgrammingError: If SQL syntax errors or missing objects.
            DatabaseError: If other database operations fail (includes OperationalError, DataError, etc.).
        """
        if not checks:
            raise InvalidCheckError("Checks cannot be empty or None.")

        engine = self.engine
        engine_created_internally = False
        if not engine:
            engine = self.get_engine(config)
            engine_created_internally = True

        try:
            self._save_checks_to_lakebase(checks, config, engine)
            logger.info(f"Successfully saved {len(checks)} checks to Lakebase.")

        except IntegrityError as e:
            logger.error(f"Integrity constraint violation while saving checks to Lakebase: {e}")
            raise

        except ProgrammingError as e:
            logger.error(f"Programming error while saving checks to Lakebase: {e}")
            raise

        except DatabaseError as e:
            logger.error(f"Database error while saving checks to Lakebase: {e}")
            raise

        finally:
            if engine_created_internally:
                engine.dispose()


class WorkspaceFileChecksStorageHandler(ChecksStorageHandler[WorkspaceFileChecksStorageConfig]):
    """
    Handler for storing quality rules (checks) in a file (json or yaml) in the workspace.
    """

    def __init__(self, ws: WorkspaceClient):
        self.ws = ws

    @telemetry_logger("load_checks", "workspace_file")
    def load(self, config: WorkspaceFileChecksStorageConfig) -> list[dict]:
        """Load checks (dq rules) from a file (json or yaml) in the workspace.
        This does not require installation of DQX in the workspace.

        Args:
            config: configuration for loading checks, including the file location and storage type.

        Returns:
            list of dq rules or raise an error if checks file is missing or is invalid.

        Raises:
            NotFound: if the checks file is not found in the workspace.
            InvalidCheckError: if the checks file cannot be parsed.
        """
        file_path = config.location
        logger.info(f"Loading quality rules (checks) from '{file_path}' in the workspace.")

        try:
            file_bytes = self.ws.workspace.download(file_path).read()
            file_content = file_bytes.decode("utf-8")
        except NotFound as e:
            raise NotFound(f"Checks file {file_path} missing: {e}") from e

        try:
            extension = get_file_extension(file_path)
            return ChecksDeserializer.deserialize_from_file(extension, StringIO(file_content)) or []
        except (yaml.YAMLError, json.JSONDecodeError) as e:
            raise InvalidCheckError(f"Invalid checks in file: {file_path}: {e}") from e

    @telemetry_logger("save_checks", "workspace_file")
    def save(self, checks: list[dict], config: WorkspaceFileChecksStorageConfig) -> None:
        """Save checks (dq rules) to yaml file in the workspace.
        This does not require installation of DQX in the workspace.

        Args:
            checks: list of dq rules to save
            config: configuration for saving checks, including the file location and storage type.
        """
        logger.info(f"Saving quality rules (checks) to '{config.location}' in the workspace.")
        file_path = Path(config.location)
        workspace_dir = str(file_path.parent)
        self.ws.workspace.mkdirs(workspace_dir)

        extension = get_file_extension(file_path)
        content = ChecksSerializer.serialize_to_bytes(checks, extension)
        self.ws.workspace.upload(config.location, content, format=ImportFormat.AUTO, overwrite=True)


class FileChecksStorageHandler(ChecksStorageHandler[FileChecksStorageConfig]):
    """
    Handler for storing quality rules (checks) in a file (json or yaml) in the local filesystem.
    """

    def load(self, config: FileChecksStorageConfig) -> list[dict]:
        """
        Load checks (dq rules) from a file (json or yaml) in the local filesystem.

        Args:
            config: configuration for loading checks, including the file location.

        Returns:
            list of dq rules or raise an error if checks file is missing or is invalid.

        Raises:
            FileNotFoundError: if the file path does not exist
            InvalidCheckError: if the checks file cannot be parsed
        """
        file_path = config.location
        logger.info(f"Loading quality rules (checks) from '{file_path}'.")

        try:
            extension = get_file_extension(file_path)
            with open(file_path, "r", encoding="utf-8") as f:
                return ChecksDeserializer.deserialize_from_file(extension, f) or []
        except FileNotFoundError as e:
            raise FileNotFoundError(f"Checks file {file_path} missing: {e}") from e
        except (yaml.YAMLError, json.JSONDecodeError) as e:
            raise InvalidCheckError(f"Invalid checks in file: {file_path}: {e}") from e

    def save(self, checks: list[dict], config: FileChecksStorageConfig) -> None:
        """
        Save checks (dq rules) to a file (json or yaml) in the local filesystem.

        Args:
            checks: list of dq rules to save
            config: configuration for saving checks, including the file location.

        Raises:
            FileNotFoundError: if the file path does not exist
        """
        logger.info(f"Saving quality rules (checks) to '{config.location}'.")
        file_path = Path(config.location)
        os.makedirs(file_path.parent, exist_ok=True)

        try:
            extension = get_file_extension(file_path)
            content = ChecksSerializer.serialize_to_bytes(checks, extension)
            with open(file_path, "wb") as file:
                file.write(content)
        except FileNotFoundError:
            msg = f"Checks file {config.location} missing"
            raise FileNotFoundError(msg) from None


class InstallationChecksStorageHandler(ChecksStorageHandler[InstallationChecksStorageConfig], InstallationMixin):
    """
    Handler for storing quality rules (checks) defined in the installation configuration.
    """

    def __init__(
        self,
        ws: WorkspaceClient,
        spark: SparkSession,
        config_serializer: ConfigSerializer | None = None,
    ):
        self.ws = ws
        self._config_serializer = config_serializer or ConfigSerializer(ws)
        self.workspace_file_handler = WorkspaceFileChecksStorageHandler(ws)
        self.table_handler = TableChecksStorageHandler(ws, spark)
        self.volume_handler = VolumeFileChecksStorageHandler(ws)
        self.lakebase_handler = LakebaseChecksStorageHandler(ws, spark, None)
        super().__init__(ws)

    @telemetry_logger("load_checks", "installation")
    def load(self, config: InstallationChecksStorageConfig) -> list[dict]:
        """
        Load checks (dq rules) from the installation configuration.

        Args:
            config: configuration for loading checks, including the run configuration name and method.

        Returns:
            list of dq rules or raise an error if checks file is missing or is invalid.

        Raises:
            NotFound: if the checks file or table is not found in the installation.
            InvalidCheckError: if the checks file cannot be parsed.
        """
        handler, config = self._get_storage_handler_and_config(config)
        return handler.load(config)

    @telemetry_logger("save_checks", "installation")
    def save(self, checks: list[dict], config: InstallationChecksStorageConfig) -> None:
        """
        Save checks (dq rules) to yaml file or table in the installation folder.
        This will overwrite existing checks file or table.

        Args:
            checks: list of dq rules to save
            config: configuration for saving checks, including the run configuration name, method, and table location.
        """
        handler, config = self._get_storage_handler_and_config(config)
        return handler.save(checks, config)

    def _get_storage_handler_and_config(
        self, config: InstallationChecksStorageConfig
    ) -> tuple[ChecksStorageHandler, InstallationChecksStorageConfig]:
        # Overwrite location if overwrite_location is set
        if config.overwrite_location:
            checks_location = config.location
        else:
            run_config = self._config_serializer.load_run_config(
                run_config_name=config.run_config_name,
                assume_user=config.assume_user,
                product_name=config.product_name,
                install_folder=config.install_folder,
            )

            checks_location = run_config.checks_location

            # transfer lakebase fields from run config to storage config if not already set
            if run_config.lakebase_instance_name and not config.instance_name:
                config.instance_name = run_config.lakebase_instance_name
            if run_config.lakebase_client_id and not config.client_id:
                config.client_id = run_config.lakebase_client_id
            # replace port if non-default is specified in the run config
            if run_config.lakebase_port and config.port != run_config.lakebase_port:
                config.port = run_config.lakebase_port

        installation = self._get_installation(
            product_name=config.product_name, assume_user=config.assume_user, install_folder=config.install_folder
        )

        config.location = checks_location

        matches_table_pattern = is_table_location(config.location)
        is_lakebase_storage = config.instance_name is not None

        if matches_table_pattern and is_lakebase_storage:
            logger.debug(f"Using LakebaseChecksStorageHandler for location '{config.location}'")
            return self.lakebase_handler, config

        if matches_table_pattern:
            logger.debug(f"Using TableChecksStorageHandler for location '{config.location}'")
            return self.table_handler, config

        if config.location.startswith("/Volumes/"):
            logger.debug(f"Using VolumeChecksStorageHandler for location '{config.location}'")
            return self.volume_handler, config

        if not config.location.startswith("/"):
            # if absolute path is not provided, the location should be set relative to the installation folder
            config.location = f"{installation.install_folder()}/{config.location}"

        logger.debug(f"Using WorkspaceFileChecksStorageHandler for location '{config.location}'")
        return self.workspace_file_handler, config


class VolumeFileChecksStorageHandler(ChecksStorageHandler[VolumeFileChecksStorageConfig]):
    """
    Handler for storing quality rules (checks) in a file (json or yaml) in a Unity Catalog volume.
    """

    def __init__(self, ws: WorkspaceClient):
        self.ws = ws

    @telemetry_logger("load_checks", "volume")
    def load(self, config: VolumeFileChecksStorageConfig) -> list[dict]:
        """Load checks (dq rules) from a file (json or yaml) in a Unity Catalog volume.

        Args:
            config: configuration for loading checks, including the file location and storage type.

        Returns:
            list of dq rules or raise an error if checks file is missing or is invalid.

        Raises:
            NotFound: if the checks file is not found in the workspace.
            InvalidCheckError: if the checks file cannot be parsed.
            CheckDownloadError: if there is an error downloading the file from the volume.
        """
        file_path = config.location
        logger.info(f"Loading quality rules (checks) from '{file_path}' in a volume.")

        try:
            file_download = self.ws.files.download(file_path)
            if not file_download.contents:
                raise CheckDownloadError(f"File download failed at Unity Catalog volume path: {file_path}")
            file_bytes: bytes = file_download.contents.read()
            if not file_bytes:
                raise NotFound(f"No contents at Unity Catalog volume path: {file_path}")
            file_content: str = file_bytes.decode("utf-8")

        except NotFound as e:
            raise NotFound(f"Checks file {file_path} missing: {e}") from e

        try:
            extension = get_file_extension(file_path)
            return ChecksDeserializer.deserialize_from_file(extension, StringIO(file_content)) or []
        except (yaml.YAMLError, json.JSONDecodeError) as e:
            raise InvalidCheckError(f"Invalid checks in file: {file_path}: {e}") from e

    @telemetry_logger("save_checks", "volume")
    def save(self, checks: list[dict], config: VolumeFileChecksStorageConfig) -> None:
        """Save checks (dq rules) to yaml file in a Unity Catalog volume.
        This does not require installation of DQX in a Unity Catalog volume.

        Args:
            checks: list of dq rules to save
            config: configuration for saving checks, including the file location and storage type.
        """
        logger.info(f"Saving quality rules (checks) to '{config.location}' in a Unity Catalog volume.")
        file_path = Path(config.location)
        volume_dir = str(file_path.parent)
        self.ws.files.create_directory(volume_dir)

        extension = get_file_extension(file_path)
        content = ChecksSerializer.serialize_to_bytes(checks, extension)
        binary_data = BytesIO(content)
        self.ws.files.upload(config.location, binary_data, overwrite=True)


class BaseChecksStorageHandlerFactory(ABC):
    """
    Abstract base class for factories that create storage handlers for checks.
    """

    @abstractmethod
    def create(self, config: BaseChecksStorageConfig) -> ChecksStorageHandler:
        """
        Abstract method to create a handler based on the type of the provided configuration object.

        Args:
            config: Configuration object for loading or saving checks.

        Returns:
            An instance of the corresponding BaseChecksStorageHandler.
        """

    @abstractmethod
    def create_for_location(
        self, location: str, run_config_name: str = "default"
    ) -> tuple[ChecksStorageHandler, BaseChecksStorageConfig]:
        """
        Abstract method to create a handler and config based on checks location.

        Args:
            location: location of the checks (file path, table name, volume, etc.).
            run_config_name: the name of the run configuration to use for checks, e.g. input table or job name (use "default" if not provided).

        Returns:
            An instance of the corresponding BaseChecksStorageHandler.
        """

    @abstractmethod
    def create_for_run_config(self, run_config: RunConfig) -> tuple[ChecksStorageHandler, BaseChecksStorageConfig]:
        """
        Abstract method to create a handler and config based on a RunConfig.

        This method inspects the RunConfig to determine the appropriate storage handler.
        If Lakebase connection parameters are present (lakebase_instance_name), it creates
        a LakebaseChecksStorageHandler. Otherwise, it delegates to create_for_location
        to infer the handler from the checks location string.

        Args:
            run_config: RunConfig containing checks location and optional Lakebase parameters.

        Returns:
            A tuple of (ChecksStorageHandler, BaseChecksStorageConfig).
        """


class ChecksStorageHandlerFactory(BaseChecksStorageHandlerFactory):
    def __init__(self, workspace_client: WorkspaceClient, spark: SparkSession):
        self.workspace_client = workspace_client
        self.spark = spark

    def create(self, config: BaseChecksStorageConfig) -> ChecksStorageHandler:
        """
        Factory method to create a handler based on the type of the provided configuration object.

        Args:
            config: Configuration object for loading or saving checks.

        Returns:
            An instance of the corresponding BaseChecksStorageHandler.

        Raises:
            InvalidConfigError: If the configuration type is unsupported.
        """
        if isinstance(config, FileChecksStorageConfig):
            return FileChecksStorageHandler()
        if isinstance(config, InstallationChecksStorageConfig):
            return InstallationChecksStorageHandler(self.workspace_client, self.spark)
        if isinstance(config, WorkspaceFileChecksStorageConfig):
            return WorkspaceFileChecksStorageHandler(self.workspace_client)
        if isinstance(config, TableChecksStorageConfig):
            return TableChecksStorageHandler(self.workspace_client, self.spark)
        if isinstance(config, LakebaseChecksStorageConfig):
            return LakebaseChecksStorageHandler(self.workspace_client, self.spark, None)
        if isinstance(config, VolumeFileChecksStorageConfig):
            return VolumeFileChecksStorageHandler(self.workspace_client)

        raise InvalidConfigError(f"Unsupported storage config type: {type(config).__name__}")

    def create_for_location(
        self, location: str, run_config_name: str = "default"
    ) -> tuple[ChecksStorageHandler, BaseChecksStorageConfig]:
        if is_table_location(location):
            return (
                TableChecksStorageHandler(self.workspace_client, self.spark),
                TableChecksStorageConfig(location=location, run_config_name=run_config_name),
            )
        if location.startswith("/Volumes/"):
            return (
                VolumeFileChecksStorageHandler(self.workspace_client),
                VolumeFileChecksStorageConfig(location=location),
            )
        if location.startswith("/"):
            return (
                WorkspaceFileChecksStorageHandler(self.workspace_client),
                WorkspaceFileChecksStorageConfig(location=location),
            )

        return FileChecksStorageHandler(), FileChecksStorageConfig(location=location)

    def create_for_run_config(self, run_config: RunConfig) -> tuple[ChecksStorageHandler, BaseChecksStorageConfig]:
        """
        Factory method to create a handler and config based on a RunConfig.

        This method inspects the RunConfig to determine the appropriate storage handler.
        If Lakebase connection parameters are present (lakebase_instance_name), it creates
        a LakebaseChecksStorageHandler. Otherwise, it delegates to create_for_location
        to infer the handler from the checks location string.

        Args:
            run_config: RunConfig containing checks location and optional Lakebase parameters.

        Returns:
            A tuple of (ChecksStorageHandler, BaseChecksStorageConfig).

        Raises:
            InvalidConfigError: If the configuration is invalid or unsupported.
        """
        if run_config.lakebase_instance_name:
            if not run_config.checks_location:
                raise InvalidConfigError(
                    f"checks_location must be specified in run config '{run_config.name}' when using Lakebase. "
                    f"Expected format: 'database.schema.table'."
                )

            if len(run_config.checks_location.split(".")) != 3:
                raise InvalidConfigError(
                    f"Invalid Lakebase table name '{run_config.checks_location}' in run config '{run_config.name}'. "
                    f"Must be in the format 'database.schema.table'. "
                    f"Example: 'my_database.my_schema.my_table'."
                )

            return (
                LakebaseChecksStorageHandler(self.workspace_client, self.spark, None),
                LakebaseChecksStorageConfig(
                    location=run_config.checks_location,
                    instance_name=run_config.lakebase_instance_name,
                    port=run_config.lakebase_port or "5432",
                    run_config_name=run_config.name,
                ),
            )

        return self.create_for_location(run_config.checks_location, run_config.name)


def is_table_location(location: str) -> bool:
    """
    True if location points to a Delta table (catalog.schema.table) and is not a file path
    with a known checks serializer extension.

    Args:
        location (str): The checks location to validate.

    Returns:
        bool: True if the location is a valid table name and not a file path, False otherwise.
    """
    return bool(TABLE_PATTERN.match(location)) and not location.lower().endswith(
        SerializerFactory.get_supported_extensions()
    )
